env:
  browser:          true
extends:            'eslint:recommended'
parserOptions:
      ecmaVersion:  6,
      sourceType:   module
      ecmaFeatures:
        jsx:        true
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
    # change the line above to unix if you are on macOS or Linux
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console:
    - off
